package com.lis.clash

object SaveFormat {
    const val LABEL_SIZE = 16
    const val GAME_DATA_SIZE = 0x8F29E
    const val DAT_SIZE = LABEL_SIZE + GAME_DATA_SIZE

    const val TILE_RECORD_COUNT = 10000
    const val TILE_RECORD_SIZE = 14
    const val TILE_RECORDS_FILE_OFFSET = LABEL_SIZE

    const val MAP_WIDTH_FILE_OFFSET = LABEL_SIZE + 140000
    const val MAP_HEIGHT_FILE_OFFSET = LABEL_SIZE + 140004
    const val MAP_VIEW_LEFT_FILE_OFFSET = LABEL_SIZE + 140008
    const val MAP_VIEW_TOP_FILE_OFFSET = LABEL_SIZE + 140012
    const val MAP_THEME_FILE_OFFSET = LABEL_SIZE + 140016
    const val ACTIVE_MISSION_FILE_OFFSET = LABEL_SIZE + 140017
    const val MISSION_FAILURE_FILE_OFFSET = LABEL_SIZE + 140021
    const val GAME_TURN_COUNTER_FILE_OFFSET = LABEL_SIZE + 140022

    const val PLAYER_RECORDS_FILE_OFFSET = LABEL_SIZE + 140024
    const val PLAYER_RECORD_COUNT = 5
    const val PLAYER_RECORD_SIZE = 1423

    const val TURN_OWNER_FILE_OFFSET = LABEL_SIZE + 147139
    const val VIEWED_PLAYER_FILE_OFFSET = LABEL_SIZE + 147143
    const val UNKNOWN_PRE_ARMY_GAP_FILE_OFFSET = LABEL_SIZE + 147147
    const val UNKNOWN_PRE_ARMY_GAP_SIZE = 27

    const val ARMY_RECORDS_FILE_OFFSET = LABEL_SIZE + 147174
    const val ARMY_RECORD_COUNT = 500
    const val ARMY_RECORD_SIZE = 725

    const val BUILDING_RECORDS_FILE_OFFSET = LABEL_SIZE + 509674
    const val BUILDING_RECORD_COUNT = 100
    const val BUILDING_RECORD_SIZE = 467

    const val OCCUPANCY_RECORDS_FILE_OFFSET = LABEL_SIZE + 556374
    const val OCCUPANCY_RECORD_COUNT = 10000
    const val OCCUPANCY_RECORD_SIZE = 2
    const val OCCUPANCY_BUILDING_INDEX_BASE = 0x8000
    const val EMPTY_OCCUPANCY = 0xFFFF

    const val TRAP_MASK_RECORDS_FILE_OFFSET = LABEL_SIZE + 576374
    const val TRAP_MASK_RECORD_COUNT = 10000
    const val TRAP_MASK_RECORD_SIZE = 1

    const val PORT_ROW_FILE_OFFSET = LABEL_SIZE + 586374
    const val PORT_COLUMN_FILE_OFFSET = LABEL_SIZE + 586378
    const val PORT_NEXT_REINFORCEMENT_TURN_FILE_OFFSET = LABEL_SIZE + 586382
    const val PORT_REINFORCEMENT_READY_FILE_OFFSET = LABEL_SIZE + 586386
    const val PORT_REINFORCEMENT_UNIT_COUNT_FILE_OFFSET = LABEL_SIZE + 586390
    const val PORT_SHORE_VARIANT_FILE_OFFSET = LABEL_SIZE + 586394

    fun requireValidDatSize(size: Int) {
        require(size == DAT_SIZE) {
            "Invalid Clash save size: $size bytes; expected exactly $DAT_SIZE bytes"
        }
    }
}
